### PR TITLE
Initial sysartifacts website for USENIX Security 2023

### PR DESCRIPTION
**Pull request by vahldiek**
Does not include the call for artifacts, but all surrounding material.

Current version is visible at: https://vahldiek.github.io/secartifacts.github.io/usenix%20sec2023

*** Do not merge yet ***

### CODE REVIEW

**Comment by vahldiek** [comment]
@cgiuffr: Updated based on feedback and finding some more small things here and there. Could you take a final look and do push the final rebase + merge button?

**Comment by cgiuffr** [comment]
Looks good to me, will merge. Only two notes:
- We shouldn't forget about adding the checklists.
- I would add the Appendix and usenixbadges Latex sources to secartifacts outside the .zip files somewhere so we can keep them versioned as well.

**Comment by vahldiek** [comment]
There are two checklists:
https://vahldiek.github.io/secartifacts.github.io/usenix%20sec2023/guide#example-review
https://vahldiek.github.io/secartifacts.github.io/usenix%20sec2023/tips#checklists

Did you mean another checklist?

I'll publicize the appendix repository repository after removing some stuff and add a link to it somewhere...

**Comment by vahldiek** [comment]
figures and downloadable content doesn't work. I'll take a look.

**Comment by cgiuffr** [comment]
Saw it just now, yes. Checklists: I misunderstood what you originally suggested. I thought there were 2 separate checklists for authors and evaluators. But what we have now looks good.

**Comment by vahldiek** [comment]
Seems to be a space issue, because of `usenix sec2023`... Will try to fix it, soon.

**Comment by vahldiek** [comment]
Fixed in https://github.com/secartifacts/secartifacts.github.io/pull/10

**Pull request merged**
