### PR TITLE
Update with CHES 2022 issues 3 and 4.

### PR DESCRIPTION
**Pull request by J08nY**

### CODE REVIEW

**Comment by vahldiek** [comment]
@J08nY the update seems to fail the rendering. Would you mind taking a look at why it doesn't render properly?

**Comment by J08nY** [comment]
Oh, I didn't try locally with Jekyll so I just hoped I got it right :) I will fix it soon.

**Comment by vahldiek** [comment]
No worries. Just fixed it, since I added something else. You seem to have created another `---` at the top. Removing them solved the problem. Variables are in between two `---`, the initial document defined 3 `---` and hence, the variables were in the actual html rendered page. Look forward to future updates and thank you for contributing to secartifacts!

**Comment by J08nY** [comment]
Oh yeah, copy paste error :)

**Pull request merged**
